name: Sketch to Fonts and Css Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install gulp -g
      - run: npm install
      - run: npm run convert
      - name: Upload Fonts and Css Result
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: dist/